### ISSUE TITLE
Reuse a single GridBagConstraints object

### ISSUE THREAD

**Issue by ahyattdev** [realcake/RiskHelper2#3]
Reuse a single GridBagConstraints object instead of defining a reference to a new one with the creation of every UI element. It leads to much cleaner code and makes it easier to use GridBagConstraints.

**Comment by ahyattdev** [comment]
You are supposed to close an issue when you fix it...

**Comment by ahyattdev** [comment]
please commit uncommitted changes if so

**Comment by seanmckdev** [comment]
I don't understand this, but it sounds like a problem you could solve

**Comment by ahyattdev** [comment]
so...leave it open until its solved. thats how GitHub issues work

**Comment by ahyattdev** [comment]
also the normie employees at GitHub added emojis. software development used to be the last safe space from emojis.
